# blockchain/config/crypto-config.yaml
# Defines all organizations and their peer/user counts

OrdererOrgs:
  - Name: Orderer
    Domain: ehr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Hospital
    Domain: hospital.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 2           # peer0 and peer1
    Users:
      Count: 3           # Admin + 3 additional users
    CA:
      Hostname: ca

  - Name: Doctor
    Domain: doctor.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3
    CA:
      Hostname: ca

  - Name: Patient
    Domain: patient.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3
    CA:
      Hostname: ca
